- name: Update apt packages
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - wget
      - tar
    state: present

- name: Create Prometheus user
  user:
    name: prometheus
    shell: /sbin/nologin

- name: Create directories for Prometheus
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Download Prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.45.0/prometheus-2.45.0.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy Prometheus binaries
  copy:
    remote_src: yes
    src: "/tmp/prometheus-2.45.0.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: '0755'
  loop:
    - prometheus
    - promtool

- name: Copy Prometheus config and consoles
  copy:
    remote_src: yes
    src: "/tmp/prometheus-2.45.0.linux-amd64/{{ item }}"
    dest: "/etc/prometheus/{{ item }}"
  loop:
    - consoles
    - console_libraries
    - prometheus.yml

- name: Create Prometheus systemd service
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=prometheus
      Group=prometheus
      Type=simple
      ExecStart=/usr/local/bin/prometheus \
        --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/var/lib/prometheus/ \
        --web.console.templates=/etc/prometheus/consoles \
        --web.console.libraries=/etc/prometheus/console_libraries

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start Prometheus
  systemd:
    name: prometheus
    enabled: yes
    state: started
