replicaCount: 2

image:
  repository: 359329123577.dkr.ecr.us-east-1.amazonaws.com/nti-app
  tag: backend
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3001

env:
  - name: AWS_REGION
    value: "us-east-1"
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: aws-secret
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: aws-secret
        key: AWS_SECRET_ACCESS_KEY

resources: {}
